//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wiizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wiizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap figure_wiimote {
            get {
                object obj = ResourceManager.GetObject("figure_wiimote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap figure_wiimote_accIR {
            get {
                object obj = ResourceManager.GetObject("figure_wiimote_accIR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A,0,64,180,66,66
        ///B,0,271,83,80,116
        ///Plus,0,19,303,36,36
        ///Minus,0,139,303,36,36
        ///Home,0,79,303,36,36
        ///One,0,71,475,52,52
        ///Two,0,71,541,52,52
        ///Up,0,81,33,30,45
        ///Down,0,81,108,30,45
        ///Left,0,36,78,45,30
        ///Right,0,111,78,45,30
        ///N_Z,0,687,211,108,82
        ///N_C,0,710,142,62,62
        ///N_STICK_UP,0,493,105,62,62
        ///N_STICK_DOWN,0,493,237,62,62
        ///N_STICK_LEFT,0,427,173,62,62
        ///N_STICK_RIGHT,0,560,173,62,62
        ///N_STICK_X,1,,,,
        ///N_STICK_Y,1,,,,
        ///IR_X,1,,,,
        ///IR_Y,1,,,,
        ///ACC_X,1,,,,
        ///ACC_Y,1,,,,
        ///N_ACC_X,1,,,,
        ///N_ACC_Y,1,,,,
        ///.
        /// </summary>
        internal static string modelRect {
            get {
                return ResourceManager.GetString("modelRect", resourceCulture);
            }
        }
    }
}
